import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata = {
  title: "Terms & Conditions | Examly.pk",
  description:
    "Terms and Conditions for using Examly.pk – Teacher paper generation and assessment platform",
};

export default function TermsAndConditions() {
  return (
    <>
      <Header />

      <main className="terms-page">

        {/* Hero Section */}
        <section className="hero-section bg-primary text-white py-5">
          <div className="container">
            <div className="row justify-content-center text-center py-5">
              <div className="col-lg-8">
                <h1 className="display-5 fw-bold mb-3">
                  Terms & Conditions
                </h1>
                <p className="lead opacity-75">
                  Please read these terms carefully before using Examly.pk
                </p>
                <small className="opacity-75">
                  Effective Date: {new Date().toLocaleDateString()}
                </small>
              </div>
            </div>
          </div>
        </section>

        {/* Content Section */}
        <section className="content-section py-5 bg-light">
          <div className="container">
            <div className="row g-4">

              {/* Introduction */}
              <div className="col-12">
                <div className="bg-white rounded-3 shadow-sm p-4">
                  <p className="text-muted mb-0">
                    Welcome to <strong>Examly.pk</strong>. By accessing or using
                    this platform, you agree to be bound by these Terms &
                    Conditions. If you do not agree with any part of these terms,
                    please do not use our services.
                  </p>
                </div>
              </div>

              {/* Eligibility */}
              <div className="col-lg-6">
                <div className="bg-white rounded-3 shadow-sm p-4 h-100">
                  <h5 className="fw-bold mb-3">
                    <i className="bi bi-person-check me-2 text-primary"></i>
                    Eligibility
                  </h5>
                  <p className="text-muted mb-0">
                    Examly.pk is intended for teachers, educators, and
                    educational institutions only. By using the platform, you
                    confirm that you are legally eligible to enter into this
                    agreement.
                  </p>
                </div>
              </div>

              {/* Account Responsibility */}
              <div className="col-lg-6">
                <div className="bg-white rounded-3 shadow-sm p-4 h-100">
                  <h5 className="fw-bold mb-3">
                    <i className="bi bi-shield-lock me-2 text-primary"></i>
                    Account Responsibility
                  </h5>
                  <p className="text-muted mb-0">
                    You are responsible for maintaining the confidentiality of
                    your account credentials and for all activities that occur
                    under your account.
                  </p>
                </div>
              </div>

              {/* Platform Usage */}
              <div className="col-12">
                <div className="bg-white rounded-3 shadow-sm p-4">
                  <h5 className="fw-bold mb-3">
                    <i className="bi bi-journal-text me-2 text-primary"></i>
                    Use of the Platform
                  </h5>
                  <p className="text-muted mb-0">
                    You agree to use Examly.pk only for lawful educational
                    purposes. Any misuse, unauthorized sharing of content, or
                    attempt to disrupt the platform is strictly prohibited.
                  </p>
                </div>
              </div>

              {/* Content Ownership */}
              <div className="col-lg-6">
                <div className="bg-white rounded-3 shadow-sm p-4 h-100">
                  <h5 className="fw-bold mb-3">
                    <i className="bi bi-file-earmark-text me-2 text-primary"></i>
                    Content Ownership
                  </h5>
                  <p className="text-muted mb-0">
                    All question papers and educational content generated by
                    users remain their intellectual property. Examly.pk does
                    not claim ownership of user-generated content.
                  </p>
                </div>
              </div>

              {/* Subscription & Payments */}
              <div className="col-lg-6">
                <div className="bg-white rounded-3 shadow-sm p-4 h-100">
                  <h5 className="fw-bold mb-3">
                    <i className="bi bi-credit-card me-2 text-primary"></i>
                    Subscription & Payments
                  </h5>
                  <p className="text-muted mb-0">
                    Paid plans are subject to the selected subscription terms.
                    All fees are non-refundable unless explicitly stated.
                    Examly.pk reserves the right to update pricing at any time.
                  </p>
                </div>
              </div>

              {/* Free Trial */}
              <div className="col-12">
                <div className="bg-warning bg-opacity-10 border border-warning rounded-3 p-4">
                  <h5 className="fw-bold text-warning mb-2">
                    <i className="bi bi-gift me-2"></i>
                    Free Trial Eligibility
                  </h5>
                  <p className="text-muted mb-2">
                    Examly.pk offers a <strong>3-month (90 days) free trial</strong>.
                    To avail the trial, users must register on the platform or
                    log in using Google and complete their profile with a
                    <strong> valid mobile number</strong>.
                  </p>
                  <p className="text-muted mb-0">
                    If an incorrect, fake, or invalid mobile number is provided,
                    Examly.pk reserves the right to suspend the free trial or
                    permanently remove the account without prior notice.
                  </p>
                </div>
              </div>

              {/* Referral Program */}
              <div className="col-12">
                <div className="bg-success bg-opacity-10 border border-success rounded-3 p-4">
                  <h5 className="fw-bold text-success mb-2">
                    <i className="bi bi-people-fill me-2"></i>
                    Referral Program
                  </h5>
                  <p className="text-muted mb-0">
                    Users who refer others using their referral code will
                    receive <strong>1 additional month of free access</strong>
                    upon successful registration of the referred user.
                    Examly.pk reserves the right to investigate and cancel
                    rewards in case of misuse or fraudulent activity.
                  </p>
                </div>
              </div>

              {/* Limitation of Liability */}
              <div className="col-12">
                <div className="bg-white rounded-3 shadow-sm p-4">
                  <h5 className="fw-bold mb-3">
                    <i className="bi bi-exclamation-triangle me-2 text-primary"></i>
                    Limitation of Liability
                  </h5>
                  <p className="text-muted mb-0">
                    Examly.pk shall not be liable for any direct, indirect, or
                    consequential damages arising from the use or inability to
                    use the platform.
                  </p>
                </div>
              </div>

              {/* Termination */}
              <div className="col-lg-6">
                <div className="bg-white rounded-3 shadow-sm p-4 h-100">
                  <h5 className="fw-bold mb-3">
                    <i className="bi bi-x-circle me-2 text-primary"></i>
                    Account Termination
                  </h5>
                  <p className="text-muted mb-0">
                    Examly.pk reserves the right to suspend or terminate any
                    account that violates these terms, without prior notice.
                  </p>
                </div>
              </div>

              {/* Changes */}
              <div className="col-lg-6">
                <div className="bg-white rounded-3 shadow-sm p-4 h-100">
                  <h5 className="fw-bold mb-3">
                    <i className="bi bi-arrow-repeat me-2 text-primary"></i>
                    Changes to Terms
                  </h5>
                  <p className="text-muted mb-0">
                    These Terms & Conditions may be updated at any time.
                    Continued use of the platform indicates acceptance of
                    updated terms.
                  </p>
                </div>
              </div>

              {/* Contact */}
              <div className="col-12">
                <div className="bg-dark text-white rounded-3 p-4 text-center">
                  <h5 className="fw-bold mb-2">Contact Us</h5>
                  <p className="opacity-75 mb-2">
                    If you have any questions regarding these Terms & Conditions:
                  </p>
                  <p className="fw-bold mb-0">
                    📧 examlypk@gmail.com
                  </p>
                </div>
              </div>

            </div>
          </div>
        </section>

      </main>

      <Footer />
    </>
  );
}
